### ISSUE TITLE
Naming of Functions

### ISSUE THREAD

**Issue by CMCDragonkai** [lyons/ExKanren#3]
I was trying to find some documentation on this on the minikanren site, but I couldn't.

What is reason for naming all the logic relations strangely?

Like:

* numbero
* membero
* distincto
* fresh

What is with all the "o"s...?

Who came up with these names?

**Comment by lyons** [comment]
The introduction to The Reasoned Schemer defines a convention of suffixing 'o' the the end of the names of relations (a superscript 'o' in print, a regular 'o' in code), and all the literature on miniKanren published since then follows this convention, so I have followed it in my code as well.

I can't find anything published that provides a reason for choosing 'o' in particular, so as far as I can tell it was arbitrarily chosen.
